basePath: /v1/inn
consumes:
- application/json
definitions:
  Info:
    properties:
      CeoName:
        type: string
      CompanyName:
        type: string
      INN:
        type: string
      KPP:
        type: string
    type: object
    x-go-package: github.com/oa-dmitriev/shtrafovnet/proto/gen/go
  Inn:
    properties:
      INN:
        type: string
    type: object
    x-go-package: github.com/oa-dmitriev/shtrafovnet/proto/gen/go
info:
  description: Package classification LegalInfoFetcher
  version: 1.0.0
paths:
  /v1/inn{INN}:
    post:
      description: Get legal info by INN
      operationId: idOfInnEndpoint
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/Inn'
      responses:
        "200":
          $ref: '#/responses/infoResponse'
      tags:
      - inn-tag
produces:
- application/json
responses:
  infoResponse:
    description: ""
    schema:
      $ref: '#/definitions/Info'
schemes:
- http
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
